version: '3.9'  # Specify the version of Docker Compose

services:
  # back:
  #   build: .
  #   command: "./main"
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   networks:
  #     - app_network

  db:
    image: docker.io/library/mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  adminer:
    image: docker.io/library/adminer:latest
    restart: always
    ports:
      - "8082:8080"
    networks:
      - app_network

  piston:
    image: ghcr.io/engineer-man/piston
    volumes:
      - piston_data:/piston
    ports:
      - "2000:2000"
    tmpfs:
      - /piston/jobs

volumes:
  mysql_data:
  piston_data:

networks:
  app_network:
    driver: bridge
